version: "3.4"

services:
  ltcoordinator:
    build:
      context: .
      dockerfile: ltcoordinator.Dockerfile
    deploy:
      replicas: 4
    networks:
      - bic-chat-nwk
    volumes:
      - "./config:/bic/config"
  ltapi:
    build:
      context: .
      dockerfile: ltapi.Dockerfile
    deploy:
      replicas: 1
    networks:
      - bic-chat-nwk
    volumes:
      - "./config:/bic/config"

networks:
  bic-chat-nwk:
    driver: bridge
